#!/usr/bin/env node
/**
 * Exports each Hairline figure as one React file you can drop into any React
 * 18+ project, shadcn style: copy it in, own it, no package, no loader.
 *
 *   node scripts/export-react.mjs [figure.js ...] [--out dir]   (default: every figure in the current folder)
 *
 * It writes <dir>/<Name>.tsx (default export/react/): the engine, the figure and a functional
 * component, in one file that imports nothing but react.
 *
 *   import { Enclave } from "@/components/hairline/Enclave";
 *   <Enclave intensity={0.5} theme="dark" onRead={(r) => setRead(r)} className="max-w-md" />
 */
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";

const SKILL = join(homedir(), ".agents/skills/hairline-create");
const { nameOf } = await import(pathToFileURL(join(SKILL, "build.mjs")).href);
const kernel = readFileSync(join(SKILL, "kernel.js"), "utf8").trimEnd();

const argv = process.argv.slice(2), at = argv.indexOf("--out");
const outDir = at >= 0 ? argv.splice(at, 2)[1] : "export/react";
const given = argv;
const files = (given.length ? given : readdirSync(".").filter((f) => f.endsWith(".js"))).filter((f) => {
  const src = readFileSync(f, "utf8");
  return /\bhairline\s*\(\s*\{/.test(src) && nameOf(src);
});
if (!files.length) {
  console.error("export-react: no figures found; pass figure files, e.g. node scripts/export-react.mjs enclave.js");
  process.exit(2);
}

const pascal = (s) => s.replace(/(^|[-_ ])(\w)/g, (_, __, c) => c.toUpperCase());

/* the figure's closing hairline({...}) call, kept as a value instead */
function figureBody(src, f) {
  const last = [...src.matchAll(/\bhairline\s*\(\s*\{/g)].at(-1);
  const tail = src.slice(last.index);
  if (!/\}\s*\)\s*;?\s*$/.test(tail)) throw new Error(`export-react: ${f} must end with its hairline({...}) call`);
  return (src.slice(0, last.index) + tail.replace(/^hairline\s*\(\s*/, "const __hairline = ").replace(/\)\s*;?\s*$/, ";")).trim();
}

const file = (Name, means, body) => `// @ts-nocheck
"use client";
/**
 * <${Name} />: ${means}
 *
 * A Hairline figure, interactive. Generated by scripts/export-react.mjs; the
 * file needs nothing but react.
 *
 *   intensity  0..1, default 0.5
 *   theme      "light" | "dark" to force one; otherwise it follows a .dark or
 *              [data-theme="dark"] ancestor, or the page's color-scheme
 *   onRead     called with the read-out as the pointer moves, e.g. "rest"
 *   ...        any other div prop: className, style, id
 *
 * It fills its width at 5:4. Colours and stroke: set --hairline-plate,
 * --hairline-hi, --hairline-edge, --hairline-mid, --hairline-lo and
 * --hairline-stroke on it or on any ancestor.
 */
import * as React from "react";

${kernel}

${body}

export type ${Name}Props = Omit<React.ComponentProps<"div">, "children"> & {
  intensity?: number;
  theme?: "light" | "dark";
  onRead?: (read: string) => void;
};

/* intensity 0..1 to the figure's own number: two straight lines that meet at 0.5 */
const __at = ([lo, mid, hi]: number[], i: number) => {
  const t = Math.min(1, Math.max(0, Number.isFinite(i) ? i : 0.5));
  return t <= 0.5 ? lo + (t / 0.5) * (mid - lo) : mid + ((t - 0.5) / 0.5) * (hi - mid);
};

export function ${Name}({ intensity = 0.5, theme, onRead, ...props }: ${Name}Props) {
  const ref = React.useRef<HTMLDivElement>(null);
  const handle = React.useRef<{ set: (v: number) => void; destroy: () => void } | null>(null);
  const latest = React.useRef({ intensity, onRead });
  latest.current = { intensity, onRead };

  React.useEffect(() => {
    const stage = ref.current;
    if (!stage) return;
    HL.inject(document);
    const svg = HL.mk("svg", { viewBox: "0 0 400 320", "aria-hidden": "true" }, stage);
    let text = "rest";
    const read = {
      get textContent() { return text; },
      set textContent(v) {
        text = v == null ? "" : String(v);
        stage.setAttribute("data-hairline-read", text);
        latest.current.onRead?.(text);
      },
    };
    handle.current = __hairline.mount({ stage, svg, read }, __at(__hairline.range, latest.current.intensity));
    return () => {
      handle.current?.destroy();
      handle.current = null;
      svg.remove();
    };
  }, []);

  React.useEffect(() => {
    handle.current?.set(__at(__hairline.range, intensity));
  }, [intensity]);

  return (
    <div
      ref={ref}
      role="img"
      aria-label={__hairline.means}
      data-hairline={__hairline.name}
      data-hairline-theme={theme}
      {...props}
    />
  );
}

export default ${Name};
`;

const out = resolve(outDir);
mkdirSync(out, { recursive: true });
const made = [];
for (const f of files) {
  const src = readFileSync(f, "utf8"), name = nameOf(src), Name = pascal(name);
  const means = (src.match(/means:\s*"((?:[^"\\]|\\.)*)"/) || [])[1] || `The ${name} figure.`;
  writeFileSync(join(out, `${Name}.tsx`), file(Name, means, figureBody(src, f)));
  made.push(`${Name}.tsx`);
}
console.log(`react  ${out}/  ${made.join(", ")}`);
